name: Run Discord Bot

on:
  schedule:
    - cron: '0 16 * * *'
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  discord-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false # 添加这行

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the Discord bot
        run: |
          python stats_bot.py
        env:
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          DISCORD_ADMIN_ID: ${{ secrets.DISCORD_ADMIN_ID }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}

      - name: Commit and push stats.json
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git add stats.json
          git commit -m "Update stats.json" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
