name: Run Discord Bot

on:
  schedule:
    - cron: '0 16 * * *'  
  push:
    branches:
      - main

permissions:
  contents: write  # 确保 GITHUB_TOKEN 有推送权限

jobs:
  discord-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the Discord bot
        run: |
          python stats_bot.py || echo "Bot execution failed"
        env:
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}  # 从 GitHub Secrets 读取频道ID
          DISCORD_ADMIN_ID: ${{ secrets.DISCORD_ADMIN_ID }}  # 从 GitHub Secrets 读取管理员ID
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}  # 从 GitHub Secrets 读取 Discord Token

      - name: Commit and push stats.json
        run: |
          git config --global user.name 'haijian06'
          git config --global user.email 'wanghaijian05@gmail.com'
          git add stats.json
          git diff --cached --exit-code || git commit -m 'Update stats.json'  # 只有在 stats.json 变动时才提交
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
